"""empty message

Revision ID: 0b51a9ce9126
Revises: 361a4a21cdbc
Create Date: 2022-09-03 17:44:03.674251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b51a9ce9126'
down_revision = '361a4a21cdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('color', sa.Enum('black', 'white', 'green', 'red', 'brown', 'gray', 'blue', 'pink', name='paircolor'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_pair')
    # ### end Alembic commands ###
