"""empty message

Revision ID: 172516787ded
Revises: c15ae0649ddf
Create Date: 2022-09-13 22:12:27.677629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "172516787ded"
down_revision = "c15ae0649ddf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wishes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_data.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "product_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wishes")
    # ### end Alembic commands ###
