"""empty message

Revision ID: 60914c58ca6d
Revises: 1a3b1d070b52
Create Date: 2022-09-03 02:15:42.120302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60914c58ca6d'
down_revision = '1a3b1d070b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
