"""empty message

Revision ID: f3ed20c620f8
Revises: e1fb741f38bc
Create Date: 2022-09-24 17:24:26.614711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ed20c620f8'
down_revision = 'e1fb741f38bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount_code')
    # ### end Alembic commands ###
